site_name: DB-Notes

nav: 
  - Home: index.md

  # SQl Related Docs
  - SQL: 
    - Learn-SQL: sql/learn-sql.md
    - SQL-Learning-Resources: sql/learning-resources.md
    - SQL-COMMANDS: sql/sql-commands.md
    - Example-table: sql/example-table.md

  # MongoDB related docs
  - MongoDB: 
    - Learn-MongoDB: mongodb/learn-mongodb.md


# Themes related code

# theme: dracula
# # site_favicon: favicon.ico

theme: pulse
# site_favicon: favicon.ico

# theme: material
# # site_favicon: favicon.ico