name: deploy-db-notes 

on:
  push:
    branches: 
      - main

permissions:
  contents: write
  
jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v3


      - name: setup python
        uses: actions/setup-python@v4
        with:
          python-version: 3.x


      - name: setup actions
        uses: actions/cache@v2
        with:
          key: ${{ github.ref }}
          path: .cache


      - name: install dependencies for mkdocs
        run: pip install mkdocs-material mkdocs-bootswatch mkdocs-dracula-theme
        # run: pip install mkdocs-bootswatch


      - name: deploy command
        run: mkdocs gh-deploy --force